report:
- output:
    screen:
    - filename: stdout
      mail: false
      temporary: true
    csv:
    - filename: mailts_{DATETIME}.csv
      mail: true
      temporary: true
  email:
    server: localhost:25
    from: from@localhost.localdomain
    subject: ""
    body: ""
    to:
    - to@localhost.localdomain
    cc:
    - cc1@localhost.localdomain
  connection:
    type: postgres
    host: localhost
    port: 5432
    user: root
    password: root
    database: vmess
  query: "select time,duration from ngcp_cdr;"

