report:
- output:
    csv:
    - filename: mailts_{DATETIME}.csv
      mail: true
      temporary: false
    xls:
    - filename: mailts_{DATETIME}.xlsx
      sheetname: sheet_{DATE}
      mail: true
      temporary: false
  email:
    server: localhost:25
    from: from@localhost.localdomain
    subject: ""
    body: ""
    to:
    - to@localhost.localdomain
    cc:
    - cc1@localhost.localdomain
    - cc2@localhost.localdomain
    - cc3@localhost.localdomain
  connection:
    type: prometheus
    user: admin
    password: admin
    url: http://localhost:9090/
    start: 1 hour ago
    end: now
    step: 60s
  header:
  - "time,instance1,instance2,instance3"
  delimiter: ","
  query: "up"

